version: "3.9"

services:
  web:
    image: ${DOCKER_REGISTRY_IP}:${DOCKER_REGISTRY_PORT}/${COMPOSE_PROJECT_NAME}${PROJECT_SEPERATOR}${WEB_CONTAINER}:production
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    env_file:
      - react.env
      - shared.env
    environment:
      - NODE_ENV=production
    command: server-prod