version: "3.9"

services:
  lightsapp:
    command: dev
    image: ${COMPOSE_PROJECT_NAME}${PROJECT_SEPERATOR}${LIGHT_CLIENT_CONTAINER}:development
    build:
      target: development
      context: ./remote-lights-pi
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - type: bind
        source: ./remote-lights-pi/src
        target: /app/src
    environment:
      - NODE_ENV=development