version: "3.9"

services:
  redis:
    image: redis:alpine
    cpus: '0.5'
    mem_limit: 100M
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure
  lightsapp:
    cpus: '0.5'
    mem_limit: 100M
    build:
      context: ./remote-lights-pi
    ports:
      - 5000:5000
      - 9229:9229
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./remote-lights-pi/src
        target: /usr/src/app/src
    env_file:
      - socket.env
      - shared.env
  webapp:
    cpus: '0.5'
    mem_limit: 100M
    build:
      context: ./remote-lights-web
    ports:
      - 3000:3000
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./remote-lights-web/src
        target: /usr/src/app/src
      - type: bind
        source: ./remote-lights-web/public
        target: /usr/src/app/public
    env_file:
      - react.env
      - shared.env

networks:
  frontend:
  backend:


