version: "3.9"

services:
  socket:
    command: start
    image: ${DOCKER_REGISTRY_IP}:${DOCKER_REGISTRY_PORT}/${COMPOSE_PROJECT_NAME}${PROJECT_SEPERATOR}${SOCKET_CONTAINER}:production
    # build:
    #   target: production
    environment:
      - NODE_ENV=production