version: "3.9"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
    deploy:
      update_config:
        delay: 10s
      restart_policy:
        condition: on-failure