version: "3.9"

services:
  socket:
    command: start
    image: ${DOCKER_REGISTRY_IP}:${DOCKER_REGISTRY_PORT}/${COMPOSE_PROJECT_NAME}${PROJECT_SEPERATOR}${SOCKET_CONTAINER}:production
    ports:
      - 5000:5000
    networks:
      - frontend
      - backend
    env_file:
      - socket.env
      - shared.env
    environment:
      - NODE_ENV=production