version: "3.9"

services:
  webapp:
    image: ${COMPOSE_PROJECT_NAME}${PROJECT_SEPERATOR}${WEB_CONTAINER}:production
    build:
      target: production
    command: server-prod
    environment:
      - NODE_ENV=production