version: "3.9"

services:
  redis:
    image: ${DOCKER_REGISTRY_IP}:${DOCKER_REGISTRY_PORT}/${COMPOSE_PROJECT_NAME}${PROJECT_SEPERATOR}${REDIS_CONTAINER}:production
    ports:
      - "6379:6379"
    networks:
      - frontend
    deploy:
      restart_policy:
        condition: on-failure